# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bcharp
tagline:          'An iOS & Angularjs blog'
description:      'The blog of Boris Charpentier, code, tech, and books'
url:              http://bcharp.github.io
baseurl:          /

author:
  name:           'Boris Charpentier'
  url:            https://twitter.com/bcharp

paginate:         5

# Custom vars
version:          42
linkedin:         https://www.linkedin.com/in/borischarpentier
github:           https://github.com/bcharp/
